import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
 /* {
    id: "rVVeLdouViU",
    video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "JSZmQxg3fos",
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "10:12",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "ufRtWGd0cXo",
    video_title:
      "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
    video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "ufRtWGd0cXo",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:18",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "7OuSRaIPOds",
    video_title:
      "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
    video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
    tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
    cover_image: "7OuSRaIPOds",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:13",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "esjJzKjx9Fo",
    video_title: "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
    video_description: `Feeling stuck, lost, or like your best years are behind you? You're not alone and you're not too late.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "esjJzKjx9Fo",
    publish_date: "2025-07-11",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:59",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "Qwwgg_qt5ew",
    video_title: "Apply logic to simplify your conditional problems",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["Coding Tips", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "Qwwgg_qt5ew",
    publish_date: "2024-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
    project_images: [],
    category: ["Shorts", "Motion Graphics", "Explainer"],
    duration: "2:44",
    software_used: ["After Effects"],
  },
  {
    id: "TiZvFO99rpw",
    video_title: "HTTP Request Explained in 1 minute",
    video_description:
      "Every time you visit a website, your browser sends an HTTP request, and the server responds. But how does this process actually work?",
    tags: ["HTTP", "Web Basics", "Networking", "Shorts"],
    cover_image: "TiZvFO99rpw",
    publish_date: "2025-02-27",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/TiZvFO99rpw?si=vUl9yE-xeKhfq8gd",
    project_images: [],
    category: ["Shorts", "Explainer", "Motion Graphics"],
    duration: "1:10",
    software_used: ["After Effects"],
  },
  {
    id: "2esQF01ob78",
    video_title: "API & API Endpoints Explained with Simple Examples",
    video_description:
      "Every time you use an app or website, APIs are working behind the scenes to fetch data. But what exactly is an API, and how do API endpoints work? 🤔 Watch this video to learn with simple examples!",
    tags: ["API", "Web Basics", "Backend", "Shorts"],
    cover_image: "2esQF01ob78",
    publish_date: "2025-03-05",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2esQF01ob78?si=SRi4j6f8LWlkHpKh",
    project_images: [],
    category: ["Shorts", "Explainer", "Motion Graphics"],
    duration: "1:24",
    software_used: ["After Effects"],
  },
  {
    id: "fH24XyxcfOc",
    video_title: "Granola to Nutritionist - Short 01",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "fH24XyxcfOc",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/fH24XyxcfOc",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:11",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "wBrkYeMlh1U",
    video_title: "Granola to Nutritionist - Short 02",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "wBrkYeMlh1U",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/wBrkYeMlh1U",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:09",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "A7O_MV3mgsI",
    video_title: "Granola to Nutritionist - Short 03",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "A7O_MV3mgsI",
    publish_date: "2025-03-07",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/A7O_MV3mgsI",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:21",
    software_used: ["Davinci Resolve", "After Effects"],
  }, */


  /* https://youtu.be/OlXUaax0NBo */
  {
    id: "OlXUaax0NBo",
    video_title: "Best Car Care | Professional Automotive Video",
    video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
    tags: [
      "Education",
      "Institute Promo",
      "Bangla Voiceover",
      "Brand Awareness",
    ],
    cover_image: "OlXUaax0NBo",
    publish_date: "2026-08-21",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/OlXUaax0NBo",
    project_images: [],
    category: ["Promo", "Motion Graphics"],
    duration: "0:33",
    software_used: ["After Effects"],
  },


  /* https://www.youtube.com/shorts/6oMcKo2dZqg */
  {
    id: "6oMcKo2dZqg",
    video_title:
      "Gym Promotional Video Edit",
    video_description: `This video is part of Skyline Media's creative portfolio and showcases our professional video editing skills for the fitness industry.`,
    tags: ["EdTech", "Product Launch", "Education Innovation", "Motion Promo"],
    cover_image: "6oMcKo2dZqg",
    publish_date: "2026-07-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/6oMcKo2dZqg",
    project_images: [],
    category: ["Promo", "Motion Graphics"],
    duration: "0:49",
    software_used: ["After Effect"],
  },

/* https://www.youtube.com/shorts/EigKkD3RnXs */
  {
    id: "EigKkD3RnXs",
    video_title: "OKMONT FINANCE | Professional Finance Video Ad",
    video_description:
      "A professionally crafted promotional video created for OKMONT Finance, designed to communicate financial services with a clean, modern, and engaging visual style.",
    tags: ["Environment", "Sustainability", "Green Revolution", "Documentary"],
    cover_image: "EigKkD3RnXs",
    publish_date: "2026-07-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/EigKkD3RnXs",
    project_images: [],
    category: ["Documentary", "Motion Graphics"],
    duration: "0:51",
    software_used: ["After Effects"],
  },


  /* https://www.youtube.com/shorts/W6SQGDt9nUQ */
  {
    id: "W6SQGDt9nUQ",
    video_title: "DIGJAM Professional Brand Video",
    video_description: `A professionally crafted video project created for DIGJAM, featuring clean visual storytelling, engaging editing, and a premium brand-focused presentation.`,
    tags: [
      "Programming Basics",
      "Education",
      "Beginner Tips",
      "Explainer Video",
    ],
    cover_image: "W6SQGDt9nUQ",
    publish_date: "2026-08-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback:
      "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
    video_link: "https://www.youtube.com/shorts/W6SQGDt9nUQ",
    project_images: [],
    category: ["Explainer", "Motion Graphics"],
    duration: "0:43",
    software_used: ["Capcut"],
  },


/* https://www.youtube.com/shorts/dDD3Ms_eAN0 */
  {
    id: "dDD3Ms_eAN0",
    video_title: "Business Email Service",
    video_description: `A professionally crafted travel video created for Dream Vacations, showcasing an engaging working style with dynamic editing, smooth transitions, and visually appealing storytelling.`,
    tags: ["Business IT", "Email Setup", "IT Services", "Promo Video"],
    cover_image: "i2JZPZ-a_tc",
    publish_date: "2026-07-23",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/dDD3Ms_eAN0",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:28",
    software_used: ["After effects"],
  },

 
 /* https://www.youtube.com/shorts/Xoe2BWgXObQ */
  {
    id: "Xoe2BWgXObQ",
    video_title: "Professional Educational Content",
    video_description:
      "A professionally crafted video created for UIIT, featuring clean editing, engaging visuals, smooth transitions, and a modern educational presentation.",
    tags: [
      "Brand Animation",
      "Logo Reveal",
      "Motion Graphics",
      "Brand Identity",
    ],
    cover_image: "Xoe2BWgXObQ",
    publish_date: "2026-07-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/shorts/Xoe2BWgXObQ",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "0:22",
    software_used: ["After Effects"],
  }, 

/* https://youtube.com/shorts/svPVus6fRFY */
  {
    id: "svPVus6fRFY",
    video_title: "Digjam Professional Brand Edit",
    video_description: `Digjam Professional Brand Edit`,
    tags: ["Web Development", "E-commerce", "Business Website", "Promo"],
    cover_image: "svPVus6fRFY",
    publish_date: "2026-07-24",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/svPVus6fRFY",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "0:21",
    software_used: ["After effects"],
  }, 

/*https://youtu.be/cXI0dHzR3dQ */
  
  {
    id: "cXI0dHzR3dQ",
    video_title: "Promotional edit",
    video_description: `This video is part of Skyline Media's creative portfolio, showcasing professional video editing and promotional content created for the healthcare industry.`,
    tags: [
      "Marketing Strategy",
      "Conversion Optimization",
      "Business Growth",
      "Ads",
    ],
    cover_image: "cXI0dHzR3dQ",
    publish_date: "2026-06-07",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/cXI0dHzR3dQ",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:12",
    software_used: ["Capcut"],
  }, 

/*https://youtu.be/uc6apZaiCfQ*/
  
  {
    id: "uc6apZaiCfQ",
    video_title: "Commercial Edit",
    video_description: `This video is part of Skyline Media's creative portfolio, showcasing a cinematic TV commercial-style edit inspired by the iconic Royal Enfield riding experience.`,
    tags: [
      "Commercial",
      "Ads",
    ],
    cover_image: "uc6apZaiCfQ",
    publish_date: "2026-06-07",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/uc6apZaiCfQ",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "0:34",
    software_used: ["After effects"],
  }, 

/* https://youtu.be/sOldZKx2fII */
  
  {
    id: "sOldZKx2fII",
    video_title:
      "Story Film TVC Ad | Cinematic Commercial Edit ",
    video_description: `At Skyline Media, we create compelling visual stories that connect with audiences and bring brands to life through creative filmmaking and professional editing.`,
    tags: ["Stress Relief", "Mental Health", "Wellness"],
    cover_image: "sOldZKx2fII",
    publish_date: "2026-06-04",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/sOldZKx2fII",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "3:30",
    software_used: ["Davinci Resolve"],
  },
];
